### ISSUE TITLE
ConcurrentModificationExceptions

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1585] opened 2022-12-17 23:24 UTC
First one:
```java
// Method called
MinecraftServer.getInstanceManager().unregisterInstance(instance)
```
```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at net.minestom.server.entity.EntityView.forManuals(EntityView.java:99)
        at net.minestom.server.entity.Entity.removeFromInstance(Entity.java:908)
        at net.minestom.server.entity.Entity.remove(Entity.java:1489)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at net.minestom.server.instance.InstanceContainer.unloadChunk(InstanceContainer.java:228)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.minestom.server.instance.InstanceManager.unregisterInstance(InstanceManager.java:114)
        at com.nexitcraft.server.world.WorldInstanceManager.lambda$removePlayer$11(WorldInstanceManager.java:230)
```

Second one:
```java
// Method called
Entity#remove()
```
```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at net.minestom.server.entity.EntityView.forManuals(EntityView.java:99)
        at net.minestom.server.entity.Entity.removeFromInstance(Entity.java:908)
        at net.minestom.server.entity.Entity.remove(Entity.java:1489)
        at com.nexitcraft.server.npc.NPCManager.despawnNPC(NPCManager.java:393)
```

**Comment by KrystilizeNevaDies** [comment] 2022-12-29 07:45
Please give us more information so we can reproduce this ourselves to fix it. Until that happens, this will be low priority.

In this case, what was done with the instance prior to unloading it, and what is the context around Entity#remove()?

**Comment by einfachBlu** [comment] 2022-12-29 09:49
All my Entities have autoViewable to false, have read somewhere that this is the reason it happens but its a bug

**Comment by GreatWyrm** [comment] 2022-12-31 02:52
Duplicate of #1526.

**Closed** 2022-12-31 02:58 UTC
