### ISSUE TITLE
Command suggestionCallback regression

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#1934] opened 2023-09-03 12:13 UTC
suggestionCallback has been broken in some situations by #1893. This has caused some of our commands not to function.

The case demonstrated here is if you have a command `/badge admin add <1> <2>` and also `/badge set <3>` this causes the suggestion of `1` to never be called upon (however the mapInput of 1 is still called). The suggestion of `2` will be called correctly and overall, the command still executes.

This is not an issue with argument 1 as if you swap 1 and 2, then 2 will be broken. It's purely because of the position of the argument and presence of `/badge set <3>`  

Reproducer code:
```java
public class VanillaTest {

    public static void main(String... args) {
        MinecraftServer minecraftServer = MinecraftServer.init();
        minecraftServer.start("0.0.0.0", 25565);

        Instance instance = MinecraftServer.getInstanceManager().createInstanceContainer();
        instance.setGenerator(unit -> unit.modifier().fillHeight(-20, 0, Block.GRASS_BLOCK));

        MinecraftServer.getGlobalEventHandler().addListener(PlayerLoginEvent.class, event -> {
            event.setSpawningInstance(instance);
            event.getPlayer().setRespawnPoint(new Pos(0, 0, 0));
        }).addListener(PlayerSpawnEvent.class, event -> event.getPlayer().setFlying(true));

        Command command = new Command("badge");
        Command addSubCommand = new Command("admin");

        ArgumentLiteral addArg = new ArgumentLiteral("add");

        Argument<String> playerArg = new ArgumentWord("player").map(s -> {
            Audiences.all().sendMessage(Component.text("A - player mapInput called"));
            return s;
        }).setSuggestionCallback((sender, context, suggestion) -> {
            Audiences.all().sendMessage(Component.text("B - player suggestion called"));
            suggestion.addEntry(new SuggestionEntry("testOne"));
        });

        Argument<String> badgeArg = new ArgumentWord("badge")
                .setSuggestionCallback((sender, context, suggestion) -> {
                    Audiences.all().sendMessage(Component.text("C - badge suggestion called"));
                    suggestion.addEntry(new SuggestionEntry("testTwo"));
                });

        addSubCommand.addSyntax((sender, context) -> sender.sendMessage("admin add command!"), addArg, playerArg, badgeArg);

        command.addSubcommand(addSubCommand);

        command.addSyntax(((sender, context) -> {
            sender.sendMessage(Component.text("Hello World!"));
        }), new ArgumentLiteral("set"), badgeArg);

        MinecraftServer.getCommandManager().register(command);
    }
}
```

**Comment by BomBardyGamer** [comment] 2023-09-03 13:33
With some debugging, I've discovered the issue, which I will post here.

The problem is that the command parser is acting like the input is the full command, and expecting all arguments to be present when parsing, which isn't the case for partially complete commands expected in tab completions.

What happens then is that, when you pass in `/badge admin add `, it gets to the `<badge>` word argument, but because it's not provided and the reader is empty, it marks it as missing and returns a `Not enough arguments` error.

This is absolutely fine when you don't have the `/badge set` command, as this error is properly propagated, and the `suggestion` method doesn't care whether there's an error, it just gets the suggestion callback of the deepest node.

The problem really becomes a problem when you add `/badge set` in, as that also errors in its own way, being an `IncompleteType` argument result. When the `Not enough arguments` error is being propagated up, it gets to the `badge` literal node, and because the error is already set from the `/badge set` error, it is not overridden, and so the error becomes the one with `/badge set`. Then, because `set` doesn't have a suggestion callback, it suggests nothing.

**Comment by spannerdev** [comment] 2023-09-03 17:53
I have found two fixes so far:
1) Instead of returning the first error encountered, return the one with the longest chain.
2) In the graph converter, handle subcommands before syntaxes

Strangely, I couldn't replicate the issue when "admin" was a Literal instead of a Command. There was another bug fixed by this PR where literals and subcommands would prevent other arguments (in this case a player entity argument) from parsing. I had fixed this by adding node priority, however, did not test that a command would run before a literal. Command arguments are actually converted to literals *before* being added to `NodeImpl`, where they are sorted. This lead me to solution 2.

I will add **solution 2**, because this makes more logical sense and has less potential impact.

I have added a test case for this bug, but I would like to add another test case for Command>Literal before this gets merged.

In the meantime, please test this with the new version: https://github.com/spannerdev/Minestom

**Comment by spannerdev** [comment] 2023-09-03 18:37
I've discovered that solution 1 *also* needs to be implemented, but not for this case. If a command is structured like:
`/foo literal1 <bar> <baz>`
`/foo literal2 <qux>`
The order in which the syntaxes are added affects which error gets shown. This is wrong. It should return the error for the longer chain. In the case of:
`/foo literal1 <bar>`
`/foo literal2 <qux>`
and input `/foo literalN `:
If N=1, chain = `[ "", "foo", "literal1", "<bar>" ]` "Not enough arguments" , size = 4
If N=2, chain = `[ "", "foo", "literal2" ]` IncompatibleType , size = 3

This would work more correctly, I think. It certainly better approximates what the old parser would have done.

This still doesn't address the issue of what happens when you have two arguments in the same position, both with suggestion callbacks, but neither did the old parser.

**Closed** 2023-09-07 12:58 UTC
