### ISSUE TITLE
Instabreaking blocks doesn't run BlockBreakEvent

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#289] opened 2021-05-15 17:17 UTC
https://cdn.discordapp.com/attachments/809040362835935242/838618645898067969/2021-05-03_04-29-19-1.mp4

Once you re-log only the ones you didn't instabreak actually appear as broken

**Comment by Uraxys** [comment] 2021-05-18 03:04
Took a look at it and checked how much it would be to get it to work, from my adventure into the code it looks like we need to check each block mined, check if it requires a special tool, if it does, then also get the speed bonus we get for using the right tool with the given block (For example, shears, you get a 15.0 speed bonus against leaves, but only 5.0 against wool).
Then calculate the efficiency enchantment + dig speed + bonus dig speed, with this we check if the mining speed is above the instant mine "level", if it is we instantly break the block & fire the event.

I started on it before I knew the things above and found out that it wasn't as easy as I first thought
Not sure what is the best solution, but I think adding a "require tool" value to the Block enum or something like that is the best way, if not then we need to add each block that requires a special tool to a set or list, but I could be wrong.

**Comment by emortaldev** [comment] 2021-07-26 14:51
Well I'd love to check if the block broken was instabroken, but how am I supposed to know if any blocks are broken if  blockbreakevent isn't triggered

**Comment by TheMode** [comment] 2021-07-26 14:54
> Well I'd love to check if the block broken was instabroken, but how am I supposed to know if any blocks are broken if blockbreakevent isn't triggered

The issue is that the client doesn't tell us when a block has been instabroken, and we currently do not have the math to check it ourselves.

**Comment by mworzala** [comment] 2024-02-09 20:19
This issue has actually regressed a bit, you now cannot even instabreak blocks.

**Comment by DasBabyPixel** [comment] 2024-08-19 19:46
I need this for a project, so I wanted to ask if anyone has started/tried some sort of fix for me to go off of?

**Comment by mworzala** [comment] 2024-11-12 08:18
Fixed in above

**Closed by mworzala** 2024-11-12 08:18 UTC
Labels: bug, confirmed
