### ISSUE TITLE
Walls don't properly connect

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#164] opened 2021-03-08 19:03 UTC
### What is the current behavior?

walls display as if connected, but aren't actually connected to any block (there's a gap between the wall and the block next to it)
Video: https://www.zak.pink/2021/03/Vivacious-Paddlefish-11433.mp4

### What is the expected behavior?

Walls will connect with no gaps

### What steps will reproduce the problem?

Place walls next to each other

### What operating system and java version is being used?

Windows / Azul Java 11

### Additional information / Possible thoughts on why this bug is happening
N/A

**Comment by TheMode** [comment] 2021-03-08 19:34
It is because Minestom doesn't manage block rule by default. There are a few in the main repo https://github.com/Minestom/Minestom/tree/master/src/main/java/net/minestom/server/instance/block/rule/vanilla and it also contains the one for wall. those placement rules need to be registered using `BlockManager#registerBlockPlacementRule`

**Comment by ZakShearman** [comment] 2021-03-09 10:16
Thx I'll try in a few hours

**Comment by ZakShearman** [comment] 2021-03-09 19:07
After enabling these block placement rules, generally things are still really buggy.

Some walls only appear after a block next to them is broken: https://zak.pink/2021/03/Meaty-Janenschia-11454.mp4
Walls aren't properly dealt with if PlayerBlockBreakEvent is cancelled: http://zak.pink/2021/03/Mintcream-Inexpectatumpleco-11455.mp4

**Comment by TheMode** [comment] 2021-03-09 19:22
I tested on master and haven't been able to reproduce, I believe that I fixed those last week, be sure that you are up-to-date

I am still noticing a few minors visual glitches because the placement rule is not perfect yet, but nothing unusable like on your videos

**Comment by ZakShearman** [comment] 2021-03-09 19:23
I just updated before recording those videos so I'm definitely up to date.

If it's of note, I used the world converter to convert the world from anvil to minestom's format.

**Comment by mworzala** [comment] 2024-02-09 20:13
Closing this pending some updated placement rules

**Closed by mworzala** 2024-02-09 20:13 UTC
Labels: bug, needs investigation
