### ISSUE TITLE
Exception while closing server

### ISSUE THREAD

**Issue by megalith52** [Minestom/Minestom#2480] opened 2024-11-14 17:10 UTC
When using MinecraftServer.stopCleanly() method while there are players on the server, the server gives an error while closing.

**Full Code**
```java
import net.minestom.server.MinecraftServer;
import net.minestom.server.command.builder.Command;

public class StopCommand extends Command {
    public StopCommand() {
        super("stop");
        setDefaultExecutor((sender, commandContext) -> {
            MinecraftServer.stopCleanly();
        });
    }
}
```

**Exception**
```
Exception in thread "" 20:02:35.112 [Thread-0] INFO net.minestom.server.ServerProcessImpl -- Minestom server stopped successfully.
java.lang.RuntimeException: java.nio.channels.AsynchronousCloseException
        at net.minestom.server.network.socket.Server.lambda$start$2(Server.java:76)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
Caused by: java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.end(ServerSocketChannelImpl.java:383)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:407)
```

**Comment by KermanIsPretty** [comment] 2024-11-14 17:15
Isn't this a duplicate of #2096?

**Comment by ImTheLion** [comment] 2024-12-01 12:53
I am having the same issue, even without having players joining the server.
The issue does not occur on the main branch, but does on the 1_21_2 branch.

Minimal reproduction code:

```java
public static void main(String[] args) throws InterruptedException {
        MinecraftServer server = MinecraftServer.init();
        server.start("0.0.0.0", 25565);
        Thread.sleep(1000L);
        MinecraftServer.stopCleanly();
    }
```

**Closed** 2024-12-03 00:26 UTC
