### ISSUE TITLE
Non solid blocks get replaced with air

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#534] opened 2021-11-20 20:13 UTC
Non solid blocks get replaced with air when a player attempts to place a block on the block face behind it.

[Video for better explaination](https://cdn.discordapp.com/attachments/715174453398601748/911708895670583326/2021-11-20_20-05-04.mp4) (I am right clicking with the TNT)

**Comment by Eoghanmc22** [comment] 2021-11-26 04:14
this is probably caused by BlockPlacementListener never checking if the block at placementPosition is non air. also how are you canceling block placements? i can only reproduce with the block getting replace with what im holding or if i cancel the event no change (the behavior shown might also be possible if minestom thinks the player is in adventure mode but the player thinks it is in survival, possibly by setting the gamemode in the login event). also idk if a simple air check is good enough to fix this because some blocks (ie tall grass) should be able to be overridden but some blocks with solid = false like saplings shouldn't be overridden (at least if you want to preserve vanilla behavior).

**Comment by emortaldev** [comment] 2021-12-10 17:51
I am cancelling the block placements by cancelling the block break and block place event when the player is in adventure mode

**Comment by CatDevz** [comment] 2022-01-04 03:39
+1 for this issue. Occurs in both Survival and Adventure

**Comment by TheMode** [comment] 2022-01-10 20:38
Fixed by 517d6a3b7c6640082716a144a24f91bab6c349be

**Closed by TheMode** 2022-01-10 20:38 UTC

**Comment by emortaldev** [comment] 2022-04-02 23:16
Reopening because the issue still appears

**Comment by CatDevz** [comment] 2022-04-03 00:24
This issue is different
