### ISSUE TITLE
Maps randomly flipping to south

### ISSUE THREAD

**Issue by bananasmoothii** [Minestom/Minestom#1746] opened 2023-02-11 22:41 UTC
I made [an example project](https://github.com/bananasmoothii/MinestomEntityRotationTests) showing how map entities randomly flip over after a certain period of time. It seems like they always flip back to `ItemFrameMeta.Orientation.NORTH`.

Here is a video of me facing the bug, along with other light bugs, a couple of times:
https://youtu.be/JqhmOCLTaJM

On this video, the map is flipping at
- [1:00](https://youtu.be/JqhmOCLTaJM?t=60)
- [2:00](https://youtu.be/JqhmOCLTaJM?t=120)
- [3:00](https://youtu.be/JqhmOCLTaJM?t=180)

(yes, timing is funny)

**Comment by Eoghanmc22** [comment] 2023-02-11 22:54
I believe this is client side. iirc the client wants the item frame's yaw and pitch to match its metadata

**Comment by bananasmoothii** [comment] 2023-02-11 23:00
Oh... Indeed, I can't reproduce the bug after setting the yaw to 180. Well, thanks !
Also, shouldn't Minestom send the yaw and pitch according to the rotation so this doesn't happen ?

**Comment by Eoghanmc22** [comment] 2023-02-11 23:04
It could be but I feel that this is something that should be documented instead of creating a special case in the code.

**Comment by emortaldev** [comment] 2023-02-11 23:05
This is a duplicate of #760

**Comment by iam4722202468** [comment] 2023-03-15 19:35
Closing because this is a duplicate. #760 explains the problem and has a fix.

**Closed by iam4722202468** 2023-03-15 19:35 UTC
